---
specfile_path: .packit_rpm/nss-mdns.spec
files_to_sync:
  - .packit.yml
  - src: .packit_rpm/nss-mdns.spec
    dest: nss-mdns.spec
upstream_package_name: nss-mdns
downstream_package_name: nss-mdns
upstream_tag_template: "v{version}"
srpm_build_deps: []
csmock_args: --cppcheck-add-flag=--enable=style

actions:
  post-upstream-clone:
    # Use the Fedora Rawhide specfile
    - "git clone https://src.fedoraproject.org/rpms/nss-mdns .packit_rpm --depth=1"
    # Drop the "sources" file so rebase-helper doesn't think it's a dist-git
    - "rm -fv .packit_rpm/sources"
    # Drop all patches
    - "sed -ri '/^Patch[0-9]+\\:.+\\.patch/d' .packit_rpm/nss-mdns.spec"
    - "sed -i '/^%build/aautoreconf -fiv' .packit_rpm/nss-mdns.spec"
    - "sed -i '/^BuildRequires: *make/aBuildRequires: autoconf' .packit_rpm/nss-mdns.spec"
    - "sed -i '/^BuildRequires: *make/aBuildRequires: libtool' .packit_rpm/nss-mdns.spec"

jobs:
- job: copr_build
  trigger: pull_request
  targets:
  - fedora-all-aarch64
  - fedora-all-i386
  - fedora-all-ppc64le
  - fedora-all-s390x
  - fedora-all-x86_64
- job: copr_build
  trigger: commit
  targets:
  - fedora-all-aarch64
  - fedora-all-i386
  - fedora-all-ppc64le
  - fedora-all-s390x
  - fedora-all-x86_64
