/*
 * display.c - Functions to manage the display buffer and convert a
 *      MIDI event to a text string for display.
 *   
 *      The display buffer is filled by the application's WndProc() 
 *      function when it receives an MM_MIDIINPUT message.  This message 
 *      is sent by the low-level callback function upon reception of a
 *      MIDI event.  When the display buffer becomes full, newly added
 *      events overwrite the oldest events in the buffer.
 */

#include <windows.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "midimon.h"
#include "circbuf.h"
#include "display.h"
       
static short OctOfs = 0;

/* MIDI event-name strings 
 */
const char szEventNames[8][24] = {
                    "Note Off",
                    "Note On",
                    "Key Aftertouch",
                    "Control Change",
                    "Program Change",
                    "Channel Aft",
                    "Pitch Bend",
                    "System Message"
                    };

const char szSysMsgNames[16][24] = {
                    "System Exclusive",
                    "MTC Quarter Frame",
                    "Song Position Ptr",
                    "Song Select",
                    "Undefined",
                    "Undefined",
                    "Tune Request",
                    "SysEx End",
                    "Timing Clock",
                    "Undefined",
                    "Start",
                    "Continue",
                    "Stop",
                    "Undefined",
                    "Active Sensing",
                    "System Reset" 
                     };

const char szNoteNames[12][3] = {
					"C ",
					"C#",
					"D ",
					"Eb",
					"E ",
					"F ",
					"F#",
					"G ",
					"G#",
					"A ",
					"Bb",
					"B "
					};
					
// The following sets the offset for displaying the octave
// the oct parm is the octave for Middle C (MIDI Note 60)
// On an absolute scale, it would be octave 5 (60/12)
// MIDI Spec calls it octave 4 => we'll default to that

void SetOctave(int octv) {
   OctOfs = octv - 5; // 60/12
   }   

int GetOctave(void) {
   return (OctOfs + 5); 
   }   
					
/* GetDisplayText - Takes a MIDI event and creates a text string for display.
 * 
 * Params:  npText - Points to a string that the function fills.
 *          lpEvent - Points to a MIDI event.
 *
 * Return:  The number of characters in the text string pointed to by npText.
 */
int GetDisplayText(LPSTR npText, LPEVENT lpEvent) {
	BYTE bStatus, bStatusRaw, bChannel, bData1, bData2, bInPort;
   char TSStr[9];
   char NBuf[5];
   LPSTR lpNB  = NBuf;
   LPSTR lpStr = TSStr;
   short octv;
    
	switch ((short)lpEvent->wDevice) 
	{
		case DEVMON:	// -1: generated by us 
			lstrcpy(lpStr, "MIDIMon "); // Use the name instead
			break;

		case DEVMSG:	// -2: text message
         return wsprintf(npText, " %s", (LPSTR)lpEvent->data);
			break;

		default:
         wsprintf(lpStr, "%08lX", lpEvent->timestamp);     
			break;
	}

   bStatusRaw  =  LOBYTE(LOWORD(lpEvent->data));
   bStatus     =  bStatusRaw & (BYTE) 0xf0;
   bChannel		= (bStatusRaw & (BYTE) 0x0f)+1; // show common form of #
   bData1      =  HIBYTE(LOWORD(lpEvent->data));
   bData2      =  LOBYTE(HIWORD(lpEvent->data));
   bInPort     =  LOBYTE(lpEvent->wDevice)+1; 

   switch(bStatus) 
   {
		/* Three byte events 
       */
      case NOTEOFF:
      case NOTEON:
            /* A note on with a velocity of 0 is a note off 
             */
         if ((bStatus == NOTEON) && (bData2 == 0))
            bStatus = NOTEOFF;
          
         if ((octv = (bData1/12)+OctOfs) < 0)
            octv = 0;
              
         return(wsprintf(npText, FORMAT3N, lpStr, bInPort, 
                         bStatusRaw, bData1, bData2, bChannel,
                         (LPSTR)szNoteNames[bData1%12], octv,
                         (LPSTR)&szEventNames[(bStatus-0x80) >> 4][0]));
         break;


      case KEYAFTERTOUCH:
      case CONTROLCHANGE:
      case PITCHBEND:
			/* A note on with a velocity of 0 is a note off 
          */
         return(wsprintf(npText, FORMAT3, lpStr, bInPort, 
                         bStatusRaw, bData1, bData2, bChannel, 
                         (LPSTR)&szEventNames[(bStatus-0x80) >> 4][0]));
         break;

      /* Two byte events 
       */
      case PROGRAMCHANGE:
      case CHANAFTERTOUCH:
         return(wsprintf(npText, FORMAT2, lpStr, bInPort, 
                         bStatusRaw, bData1, bChannel, 
                         (LPSTR)&szEventNames[(bStatus-0x80) >> 4][0]));
         break;

      /* MIDI system events (0xf0 - 0xff) 
       */
      case SYSTEMMESSAGE:
         switch(bStatusRaw) 
         {
             /* Two byte system events 
              */
				case MTCQUARTERFRAME:
            case SONGSELECT:
               return(wsprintf(npText, FORMAT2X, lpStr, bInPort, 
                                    bStatusRaw, bData1, 
                                    (LPSTR)&szSysMsgNames[(bStatusRaw & 0x0f)][0]));
               break;

            /* Three byte system events 
             */
            case SONGPOSPTR:
               return(wsprintf(npText, FORMAT3X, lpStr, bInPort, 
                               bStatusRaw, bData1, bData2,
                               (LPSTR)&szSysMsgNames[(bStatusRaw & 0x0f)][0]));
               break;

            /* One byte system events 
             */
            default:
               return(wsprintf(npText, FORMAT1X, lpStr, bInPort, 
                               bStatusRaw,
                         		(LPSTR)&szSysMsgNames[(bStatusRaw & 0x0f)][0]));
               break;
         }
         break;
            
      default:
         return(wsprintf(npText, FORMAT3X, lpStr, bInPort, 
                         bStatusRaw, bData1, bData2, (LPSTR)"Unknown Event"));
         break;
    }
}

/* AddDisplayEvent - Puts a MIDI event in the display buffer.  The display
 *      buffer is a circular buffer.  Once it is full, newly added events
 *      overwrite the oldest events in the buffer.
 *
 * Params:  lpBuf - Points to the display buffer.
 *          lpEvent - Points to a MIDI event.
 *
 * Return:  void
 */
void AddDisplayEvent(LPDISPLAYBUFFER lpBuf, LPEVENT lpEvent)
{
	 // see if existing data needs freeing
	 if (lpBuf->lpHead->wDevice == (WORD)DEVMSG) {
		 free((char* )lpBuf->lpHead->data);
		 lpBuf->lpHead->wDevice = 0; // mark as freed
		 }

    /* Put the event in the buffer, bump the head pointer and byte count.
     */
    *lpBuf->lpHead = *lpEvent;

	 // see if new data needs copying
	 if (lpEvent->wDevice == (WORD)DEVMSG) 
		 lpBuf->lpHead->data = (DWORD)STRDUP( (LPSTR)lpEvent->data );
	 
    ++lpBuf->lpHead;
    ++lpBuf->dwCount;

    /* Wrap pointer, if necessary.
     */
    if(lpBuf->lpHead == lpBuf->lpEnd)
        lpBuf->lpHead = lpBuf->lpStart;
    
    /* A full buffer is a full buffer, no more.
     */
    lpBuf->dwCount = min(lpBuf->dwCount, lpBuf->dwSize);
}


/* GetDisplayEvent - Retrieves a MIDI event from the display buffer.  
 *      Unlike the input buffer, the event is not removed from the buffer.
 *
 * Params:  lpBuf - Points to the display buffer.
 *          lpEvent - Points to an EVENT structure that is filled with
 *              the retrieved MIDI event.
 *          wNum - Specifies which event to retrieve.
 *
 * Return:  void
 */
void GetDisplayEvent(LPDISPLAYBUFFER lpBuf, LPEVENT lpEvent, UINT wNum)
{
    LPEVENT lpFirstEvent, lpThisEvent;
    
    /* Get pointer to the first (oldest) event in buffer.
     */
    if(lpBuf->dwCount < lpBuf->dwSize)      // buffer is not yet full
        lpFirstEvent = lpBuf->lpStart;
    
    else                                    // buffer is full
        lpFirstEvent = lpBuf->lpHead;
    
    /* Offset pointer to point to requested event; wrap pointer.
     */
    lpThisEvent = lpFirstEvent + wNum;
    if(lpThisEvent >= lpBuf->lpEnd)
        lpThisEvent = lpBuf->lpStart + (lpThisEvent - lpBuf->lpEnd);
    
    /* Get the requested event.
     */
    *(lpEvent) = *lpThisEvent;
}

/* AllocDisplayBuffer - Allocates memory for a DISPLAYBUFFER structure 
 *      and a buffer of the specified size.  Each memory block is allocated 
 *      with GlobalAlloc() using GMEM_SHARE and GMEM_MOVEABLE flags and 
 *      locked with GlobalLock().  Since this buffer is only accessed by the
 *      application, and not the low-level callback function, it does not
 *      have to be page locked.
 *
 * Params:  dwSize - The size of the buffer, in events.
 *
 * Return:  A pointer to a DISPLAYBUFFER structure identifying the 
 *      allocated display buffer.  NULL if the buffer could not be allocated.
*/
LPDISPLAYBUFFER AllocDisplayBuffer(DWORD dwSize)
{
    HANDLE hMem;
    LPDISPLAYBUFFER lpBuf;
    LPEVENT lpMem;
    
    /* Allocate and lock a DISPLAYBUFFER structure.
     */
    hMem = GlobalAlloc(GMEM_SHARE | GMEM_MOVEABLE,
                       (DWORD)sizeof(DISPLAYBUFFER));
    if(hMem == NULL)
        return NULL;

    lpBuf = (LPDISPLAYBUFFER)GlobalLock(hMem);
    if(lpBuf == NULL)
    {
        GlobalFree(hMem);
        return NULL;
    }

    /* Save the handle.
     */
    lpBuf->hSelf = hMem;
    
    /* Allocate and lock memory for the actual buffer.
     */
    hMem = GlobalAlloc(GMEM_SHARE | GMEM_MOVEABLE, dwSize * sizeof(EVENT));
    if(hMem == NULL)
    {
        GlobalUnlock(lpBuf->hSelf);
        GlobalFree(lpBuf->hSelf);
        return NULL;
    }
    lpMem = (LPEVENT)GlobalLock(hMem);
    if(lpMem == NULL)
    {
        GlobalFree(hMem);
        GlobalUnlock(lpBuf->hSelf);
        GlobalFree(lpBuf->hSelf);
        return NULL;
    }

    /* Set up the DISPLAYBUFFER structure.
     */
    lpBuf->hBuffer = hMem;
    lpBuf->wError = 0;
    lpBuf->dwSize = dwSize;
    lpBuf->dwCount = 0L;
    lpBuf->lpStart = lpMem;
    lpBuf->lpEnd = lpMem + dwSize;
    lpBuf->lpTail = lpMem;
    lpBuf->lpHead = lpMem;
        
    return lpBuf;
}

/* FreeDisplayBuffer - Frees the memory for a display buffer.
 *
 * Params:  lpBuf - Points to the DISPLAYBUFFER to be freed.
 *
 * Return:  void
 */
void FreeDisplayBuffer(LPDISPLAYBUFFER lpBuf)
{
    HANDLE hMem;
    
    /* Unlock and free the buffer itself.
     */
    GlobalUnlock(lpBuf->hBuffer);
    GlobalFree(lpBuf->hBuffer);
    
    /* Unlock and free the DISPLAYBUFFER structure.
     */
    hMem = lpBuf->hSelf;
    GlobalUnlock(hMem);
    GlobalFree(hMem);
}

/* ResetDisplayBuffer - Empties a display buffer.
 *
 * Params:  lpBuf - Points to a display buffer.
 *
 * Return:  void
 */
void ResetDisplayBuffer(LPDISPLAYBUFFER lpBuf)
{
    /* Reset the pointers and event count.
     */
    lpBuf->lpHead = lpBuf->lpStart;
    lpBuf->lpTail = lpBuf->lpStart;
    lpBuf->dwCount = 0L;
    lpBuf->wError = 0;
}                     

  